"""empty message

Revision ID: bd8019816244
Revises: c33f7b1841b9
Create Date: 2024-05-13 13:32:17.712831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8019816244'
down_revision = 'c33f7b1841b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('scientificf_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('conservation_status', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('native_habitat', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('fun_facts', sa.Text(), nullable=True))
        batch_op.drop_constraint('reptiles_reptile_name_key', type_='unique')
        batch_op.drop_column('reptile_name')
        batch_op.drop_column('information')
        batch_op.drop_column('submitter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('information', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reptile_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('reptiles_reptile_name_key', ['reptile_name'])
        batch_op.drop_column('fun_facts')
        batch_op.drop_column('native_habitat')
        batch_op.drop_column('conservation_status')
        batch_op.drop_column('scientificf_name')
        batch_op.drop_column('common_name')

    # ### end Alembic commands ###
